config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root "neighborhoods#index"
  devise_for :users

  namespace :admin do
    resources :neighborhoods, only: [:index, :create, :destroy]
    resources :users, only: [:edit, :update, :destroy]
  end

  resources :neighborhoods, except: [:new, :create, :destroy] do
    resources :reviews, except: [:index, :show, :new]
  end

  resources :reviews, except: :show do
    resources :upvotes, only: [:create, :update]
    resources :downvotes, only: [:create, :update]
    resources :votes, only: [:update]
  end
end

app/models/neighborhood.rb
class Neighborhood < ActiveRecord::Base
  belongs_to :user
  has_many :reviews
  mount_uploader :image, AvatarUploader

  LOCATIONS = %w(North Northeast East South Southwest Southeast West)

  validates :name, presence: true, uniqueness: true, length: { in: 4..30 }
  validates :location, presence: true, inclusion: { in: LOCATIONS }
  validates :description, length: { in: 2..600 }, allow_blank: true
  validates :user, presence: true

  def editable_by?(user)
    user == self.user || user.try(:admin?)
  end

  def destroyable_by?(user)
    user.admin?
  end

  def self.order_by_name(page)
    order(:name).page(page).per(9)
  end

  def self.search(search)
    if search
      where(["name ILIKE ?", "%#{search}%"])
    else
      all
    end
  end
end

app/controllers/admin/neighborhoods_controller.rb
module Admin
  class NeighborhoodsController < ApplicationController
    def index
      if current_user.try(:admin?)
        @neighborhoods = Neighborhood.page(params[:page]).per(10)
        @neighborhood = Neighborhood.new
        @users = User.page(params[:page]).per(10)
      else
        redirect_to neighborhoods_path,
          notice: "You don't have access to this page!"
      end
    end

    def create
      @neighborhood = Neighborhood.new(neighborhood_params)
      @neighborhood.user = current_user
      if @neighborhood.save
        redirect_to admin_neighborhoods_path, notice: "Neighborhood Added!"
      else
        @errors = @neighborhood.errors.full_messages
        render :index
      end
    end

    def destroy
      @neighborhood = Neighborhood.find(params[:id])
      if @neighborhood.destroyable_by?(current_user)
        @neighborhood.destroy
        flash[:notice] = "Neighborhood has been deleted"
        redirect_to admin_neighborhoods_path
      end
    end

    protected

    def neighborhood_params
      params.require(:neighborhood).permit(:name, :location, :description, :image)
    end
  end
end

app/controllers/neighborhoods_controller.rb
class NeighborhoodsController < ApplicationController
  before_action :authenticate_user!, except: [:index, :show]

  def index
    @neighborhoods = Neighborhood.
      search(params[:search]).
      order_by_name(params[:page])

    if @neighborhoods.empty? && params[:search]
      redirect_to neighborhoods_path, notice: "Search returned no results."
    end
  end

  def show
    @neighborhood = Neighborhood.find(params[:id])
    @reviews = @neighborhood.
      reviews.
      order(created_at: :desc).
      page(params[:page]).
      per(25)
    @review = Review.new
  end

  def edit
    @neighborhood = Neighborhood.find(params[:id])
  end

  def update
    @neighborhood = Neighborhood.find(params[:id])
    if @neighborhood.editable_by?(current_user) &&
        @neighborhood.update_attributes(neighborhood_params)
      redirect_to neighborhood_path(@neighborhood),
        notice: "Neighborhood Edited!"
    else
      @errors = @neighborhood.errors.full_messages
      render :edit
    end
  end

  protected

  def neighborhood_params
    params.require(:neighborhood).permit(:name, :location, :description, :image)
  end
end

app/views/neighborhoods/edit.html.erb
<%= render 'shared/errors' if @errors%>

<div class='small-12 columns'>
  <h1>Edit Neighborhood</h1>
  <%= form_for @neighborhood, html: {multipart: true} do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>

    <%= f.label :location %>
    <%= f.select :location,
        Neighborhood::LOCATIONS,
        :include_blank => "Please Choose A Location" %>

    <%= f.label :description %>
    <%= f.text_area :description %>

    <%= f.file_field :image %>

    <%= f.submit "Submit" %>
  <% end %>
</div>

app/views/neighborhoods/index.html.erb
<%= render 'shared/errors' if @errors%>

<fieldset class="tagline">
  <div class="bg"></div>
  <div class="neigh"><h1>LOVE YOUR</h1></div>
  <div class="hood"><h1>NEIGHBORHOOD</h1></div>
</fieldset>

<div class="row">
  <% @neighborhoods.each do |neighborhood| %>
    <div class="large-4 columns" id="neighborhood-list">
      <%= image_tag neighborhood.image.url, size: "150x150" %>
      <div class="row labelrow">
        <div class="small-12 columns"><%= link_to neighborhood.name, neighborhood_path(neighborhood) %></div>
        <div class="small-12 columns"><%= neighborhood.location.upcase %></div>
      </div>
    </div>
  <% end %>
  <%= paginate @neighborhoods %>
</div>

<div class="row">
  <div class="small-12 columns" id="contributors">
    <div class="small-12 columns ">
        <p>
          Contributors:
        </p>
      </div>
      <div class="small-12 columns">
        <ul class="inline-list" id="pics">
          <li><%= link_to image_tag('https://media.licdn.com/mpr/mpr/shrink_200_200/AAEAAQAAAAAAAANcAAAAJDM2Nzg1MTAwLTdmYzEtNDcwMC04ODU4LWYzYTAxZTQ3NTEwOQ.jpg', size: "120x120"), "https://github.com/lizmorr", target: "_blank" %></li>
          <li><%= link_to image_tag('https://media.licdn.com/mpr/mpr/shrinknp_200_200/AAEAAQAAAAAAAAI9AAAAJDZhZjRhNmM2LWNkYTEtNDc5ZS1iNzc0LWFjZjFmOTlmMTk0ZQ.jpg', size: "120x120"), "https://github.com/kyjoya", target: "_blank" %></li>
          <li><%= link_to image_tag('https://media.licdn.com/mpr/mpr/shrink_200_200/AAEAAQAAAAAAAAKjAAAAJDBkODUzNDc2LWY1N2UtNDU5Yi05NWQxLWUzNGQxNTNiNjM4NQ.jpg', size: "120x120"), "https://github.com/Dodie324", target: "_blank" %></li>
          <li><%= link_to image_tag('https://media.licdn.com/mpr/mpr/shrink_200_200/p/4/005/0b9/00f/0bcc8b0.jpg', size: "120x120"), "https://github.com/ectomorph314", target: "_blank" %></li>
        </ul>
      </div>
    </div>
</div>

app/views/neighborhoods/new.html.erb
<%= form_for @neighborhood, html: { multipart: true} do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :location %>
  <%= f.select :location,
      Neighborhood::LOCATIONS,
      include_blank: "Please Choose A Location" %>

  <%= f.label :description %>
  <%= f.text_area :description %>

  <%= f.label :image %>
  <%= f.file_field :image %>

  <%= f.submit "Submit" %>
<% end %>

app/views/neighborhoods/show.html.erb
<%= render 'shared/errors' if @errors%>

<div class="row" id="neighborhood">
  <div class="small-12 columns" id="neighborhood_header">
    <div class="small-8 columns">
      <h1><%= @neighborhood.name %></h1>
        <% if @neighborhood.editable_by?(current_user) %>
          <%= link_to "Edit Page", edit_neighborhood_path(@neighborhood) %>
        <% end %>
      <h4><%= @neighborhood.location %></h4>
      <%= image_tag @neighborhood.image_url.to_s, class: "one_neighborhood" %>
    </div>
      <div class="small-4 columns" id="neighborhood_info">
        <%= @neighborhood.description %>
      </div>
  </div>

  <div class="small-12 columns" id="ratings_list">
    <%= render "reviews/index" if @reviews %>
  </div>

  <div class="small-12 columns">
    <%= render "reviews/new" %>
  </div>
</div>