config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root "neighborhoods#index"
  devise_for :users

  namespace :admin do
    resources :neighborhoods, only: [:index, :create, :destroy]
    resources :users, only: [:edit, :update, :destroy]
  end

  resources :neighborhoods, except: [:new, :create, :destroy] do
    resources :reviews, except: [:index, :show, :new]
  end

  resources :reviews, except: :show do
    resources :upvotes, only: [:create, :update]
    resources :downvotes, only: [:create, :update]
    resources :votes, only: [:update]
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :neighborhoods
  has_many :reviews
  has_many :votes
  mount_uploader :image, AvatarUploader

  ROLES = %w(member admin)

  validates :role, presence: true, inclusion: { in: ROLES }
  validates :username, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  def admin?
    role == 'admin'
  end

  def editable_by?(user)
    user.admin?
  end

  def destroyable_by?(user)
    user.admin?
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < ApplicationController
    def edit
      if current_user.try(:admin?)
        @user = User.find(params[:id])
      else
        redirect_to neighborhoods_path,
          notice: "You don't have access to this page!"
      end
    end

    def update
      @user = User.find(params[:id])
      if @user.update_attributes(user_params)
        flash[:notice] = "User updated!"
        redirect_to admin_neighborhoods_path
      end
    end

    def destroy
      @user = User.find(params[:id])
      if @user.destroyable_by?(current_user)
        @user.destroy
        flash[:notice] = "User has been deleted"
        redirect_to admin_neighborhoods_path
      end
    end

    protected

    def user_params
      params.require(:user).permit(:role)
    end
  end
end

app/views/admin/users/_index.html.erb
<% if @users %>
  <%= paginate @users %>
  <% @users.each do |user| %>
    <div id="user_<%= user.id %>">
      <h2><%= user.username %></h2>
      <p><%= user.email %></p>
      <div class="small-6 columns">
        <%= link_to "Edit this User", edit_admin_user_path(user) %>
      </div>

      <div class="small-6 columns">
        <div id="delete">
          <%= link_to "Delete this User", admin_user_path(user), method: :delete %>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

app/views/admin/users/edit.html.erb
<div class="small-12 columns">
  <h1>Edit <%= @user.email %><h2>

  <%= form_for(@user, url: [:admin, @user]) do |f| %>

    <%= f.radio_button(:role, "member") %>
    <%= f.label(:role_member, "Member") %>

    <%= f.radio_button(:role, "admin") %>
    <%= f.label(:role_admin, "Admin") %>

    <%= f.submit "Edit User" %>
  <% end %>
</div>