config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root "neighborhoods#index"
  devise_for :users

  namespace :admin do
    resources :neighborhoods, only: [:index, :create, :destroy]
    resources :users, only: [:edit, :update, :destroy]
  end

  resources :neighborhoods, except: [:new, :create, :destroy] do
    resources :reviews, except: [:index, :show, :new]
  end

  resources :reviews, except: :show do
    resources :upvotes, only: [:create, :update]
    resources :downvotes, only: [:create, :update]
    resources :votes, only: [:update]
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def edit
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
    @review = @neighborhood.reviews.find(params[:id])
  end

  def create
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
    @review = Review.new(review_params)
    @review.neighborhood = @neighborhood
    @review.user = current_user

    if @review.save
      ReviewNotifier.new_review(@review).deliver
      flash[:notice] = "Review added successfully."
      redirect_to neighborhood_path(@neighborhood)
    else
      @errors = @review.errors.full_messages
      render "neighborhoods/show"
    end
  end

  def update
    @review = Review.find(params[:id])
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
    if @review.update(review_params)
      flash[:notice] = "Review updated!"
      redirect_to neighborhood_path(@review.neighborhood_id)
    else
      @errors = @review.errors.full_messages
      render :edit
    end
  end

  def destroy
    @neighborhood = Neighborhood.find(params[:neighborhood_id])
    @review = Review.find(params[:id])
    if @review.user == current_user || current_user.admin?
      @review.destroy
      flash[:notice] = "Review deleted"
      redirect_to neighborhood_path(@neighborhood)
    end
  end

  protected

  def review_params
    params.require(:review).permit(:rating, :description)
  end
end

app/views/reviews/_index.html.erb
<%= paginate @reviews %>
<% @reviews.each do |review| %>
  <div class="row">
    <div class="rating">

      <ul class="inline-list" id="review_details">
        <li class="profile-picture"><%= image_tag review.user.image.url, size: "60x60" %></li>
        <li class="review_description"><%= review.description %></li>
      </ul>

      <ul class="inline-list">
         <% review.rating.times do %>
         <li><%= image_tag("star-on.png") %></li>
         <% end %>
      </ul>

      <ul class="inline-list" id="vote_links">
        <% if current_user %>
          <% if review.voted_on_by?(current_user) && review.find_vote(current_user).value == 0 %>
            <li class="upvote"><%= link_to "Upvote", review_upvote_path(review, review.find_vote(current_user)), method: :patch %></li>
            <li class="downvote"><%= link_to "Downvote", review_downvote_path(review, review.find_vote(current_user)), method: :patch %></li>
          <% elsif review.voted_on_by?(current_user) %>
              Already voted. <li class="cancel"><%= link_to "Cancel.",
              review_vote_path(review, review.find_vote(current_user)), method: :patch %></li>
          <% else %>
            <li class="upvote"><%= link_to "Upvote", review_upvotes_path(review), method: :post %></li>
            <li class="downvote"><%= link_to "Downvote", review_downvotes_path(review), method: :post %></li>
          <% end %>
        <% end %>
      </ul>

      <p id="vote_count">Votes: <%= review.total_votes %></p>

      <ul class="inline-list" id="edit_links">
        <% if review.editable_by?(current_user) %>
          <li><%= link_to "Edit Review", edit_neighborhood_review_path(review.neighborhood, review)  %></li>
        <% end %>
        <% if review.deletable_by?(current_user) %>
          <li><%= link_to "Delete Review", neighborhood_review_path(review.neighborhood, review), method: :delete %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

app/views/reviews/_new.html.erb
<%= form_for [@neighborhood, @review] do |f| %>
  <%= f.label :rating %>
  <%= f.hidden_field :rating %>
  <div id="star-ratings"></div>

  <%= f.label :description, "Review" %>
  <%= f.text_area :description %>

  <%= f.submit "Add Review", class: "button radius" %>
<% end %>

<%= content_for :extra_footer do %>
  <script type="text/javascript">

  </script>
<% end %>

app/views/reviews/edit.html.erb
<%= render 'shared/errors' if @errors%>

<%= form_for [@neighborhood, @review] do |f| %>
  <%= f.label :rating %>
  <%= f.hidden_field :rating %>
  <div id="star-ratings"></div>

  <%= f.label :description, "Review" %>
  <%= f.text_area :description %>

  <%= f.submit "Edit Review" %>
<% end %>

app/views/reviews/index.html.erb
<% @reviews.each do |review| %>
  <div class="review" id="<%= review.id %>">
    <%= review.rating %>
    <%= review.description %>
    <%= review.user.email %>
  </div>
<% end %>

app/views/reviews/new.html.erb
<%= form_for [@neighborhood, @review] do |f| %>
  <%= f.label :rating %>
  <% Review::RATING.each do |rating| %>
    <%= f.radio_button(:rating, rating) %>
    <%= f.label("rating_#{rating}",rating) %>
  <% end %>

  <%= f.label :description, "Review" %>
  <%= f.text_area :description %>

  <%= f.submit "Add Review" %>
<% end %>