config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root "neighborhoods#index"
  devise_for :users

  namespace :admin do
    resources :neighborhoods, only: [:index, :create, :destroy]
    resources :users, only: [:edit, :update, :destroy]
  end

  resources :neighborhoods, except: [:new, :create, :destroy] do
    resources :reviews, except: [:index, :show, :new]
  end

  resources :reviews, except: :show do
    resources :upvotes, only: [:create, :update]
    resources :downvotes, only: [:create, :update]
    resources :votes, only: [:update]
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Neighborgood</title>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="fixed">
    <nav class="top-bar" data-topbar role="navigation">
      <ul class="title-area">
        <li class="name">
          <h1><a href="/">Neighborgood</a></h1>
        </li>
      </ul>

      <ul class="left">
        <div id="search-icon"><i class="fi-magnifying-glass"></i></div>
          <div id="search-box">
            <div class="large-10 columns">
              <div class="row collapse postfix-round">
                  <div class="small-7 columns">
                    <%= form_tag neighborhoods_path, method: :get, class: "searchbox-input" do %>
                    <%= text_field_tag :search, params[:search], placeholder: "Search Neighborhoods", id: "search-box-field" %>
                  </div>
                  <div class="small-5 columns">
                    <%= submit_tag "Search", name: nil, class: "button radius" %>
                    <% end %>
                  </div>
              </div>
            </div>
          </div>
      </ul>
      <ul class="right">
        <%- if current_user.try(:admin?) %>
          <li><%= link_to 'Admin Home', admin_neighborhoods_path %></li>
        <%- end %>
        <%- if current_user -%>
          <li><%= image_tag current_user.image.url, size: "30x30" %></li>
          <li><%= link_to 'Edit Info', edit_user_registration_path %></li>
          <li><%= link_to 'Sign Out', destroy_user_session_path, method: :delete %></li>
        <%- else -%>
          <li><%= link_to 'Sign Up', new_user_registration_path %></li>
          <li><%= link_to 'Log In', new_user_session_path %></li>
        <%- end -%>
      </ul>
    </nav>
  </div>

  <%- flash.each do |key, value| -%>
    <div class="flash flash-<%= key %>">
      <div class="text"><%= value.html_safe %></div>
    </div>
  <%- end -%>

    <%= yield %>

  <%= javascript_include_tag 'application' %>
  <%= yield :extra_footer %>
</body>
</html>